Algoritmo "exercicio07"
// O programa deverá ler e somar números até que o valor
// digitado seja zero ( 0 )
// Autor(a)    : Julia Gferri

Var
num,soma:inteiro


Inicio
repita
       escreval("Digite um número: ")
        leia(num)
        soma<- soma+num
ate (num=0)
escreval("-------------------------------------------------")
escreval("O resultado da soma dos números digitados é: ",soma)


Fimalgoritmo