algoritmo "exercicio10"
// Escreva um programa que lido um número, calcule e informe o seu fatorial
// Autor(a)    : Julia Gferri

var
num, cont, fatorial : inteiro


inicio
escreval ("Digite um número: ")
leia (num)

cont <- 1
fatorial <- 1

enquanto cont <= num faca
         fatorial <- fatorial * cont
         cont <- cont +1
fimenquanto

escreval ("O fatorial de", num ," é: ", fatorial)

FimAlgoritmo