Algoritmo "exercicio15"
// peça ao usuário para digitar a melhor escola de Ribeirão Pires
// O programa só termina se ele digitar ETEC MCM.
// Autor(a)    : Julia Gferri
Var
escola:caractere


Inicio
escreval("· Escreva qual é a melhor escola de Ribeirão Pires ·")
leia(escola)

enquanto (escola<>"Etec MCM") faca
         escreval("Tente novamente...")
         leia(escola)
fimenquanto

Fimalgoritmo